Add b2aipreview to appropriate dashboard tab
eipm/bridge2ai-docs pull request #12
Opened 2024-10-23 18:48 UTC by ibevers

2024-10-23 20:09 UTC, alexsigaras requested changes
Hi @ibevers,

Could you please add the .html portion referenced in the `src/dashboard.py` as a static project resource rather than a relative link? We would like to ensure that all content displayed on this project is contained within and there are no external dependencies

2024-10-30 18:56 UTC, ibevers commented
@alexsigaras I have integrated the html file locally, as well as the template directory structure. The ref to the directory structure refs my fork currently since there isn't a checksum associated with it yet on the source repo. This can be updated once this is merged so that everything is local to this repo.

2024-11-08 14:04 UTC, alexsigaras commented on src/dashboard.py
> +        # "Study Dashboard": study_dashboard_page,
```suggestion
        "Study Dashboard": study_dashboard_page,
```

2024-11-08 14:04 UTC, alexsigaras commented on src/dashboard.py
> +# from tabs.study_dashboard import study_dashboard_page
```suggestion
from tabs.study_dashboard import study_dashboard_page
```

2024-11-08 14:52 UTC, alexsigaras approved these changes
🚀

2024-11-08 14:52 UTC, merged